-MM
src/CIntervalAnswer.cpp
src/CManager.cpp
src/CMultiChoiceQuestion.cpp
src/CMultipleChoiceAnswer.cpp
src/CQuiz.cpp
src/CSection.cpp
src/CSingleChoiceQuestion.cpp
src/CTextAnswer.cpp
src/CTextQuestion.cpp
src/CTrueFalseAnswer.cpp
src/CXMLBuilder.cpp
src/CXMLParser.cpp
src/main.cpp
